import type { Metadata } from "next";
import { GoogleAnalytics } from "@next/third-parties/google";
import Header from "../components/Header";
import Footer from "../components/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "yellow sunflower",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Header />
      <body>{children}</body>
      <GoogleAnalytics gaId="G-H74DH7K4E4" />
      <Footer />
    </html>
  );
}
